### PR TITLE
New spec proposal

### PR DESCRIPTION
**Pull request by stefanmaric**
This is a long-running PR to rewrite node-scrapy.

Let's start with some spec tests.

### CODE REVIEW

**Comment by stefanmaric** [comment]
This spec proposal aims to solve the biggest concern among `node-scrapy` users: the inability to represent arrays of objects in the model. As pointed out in #16 and #8, and expressed by several developers via email.

This proposal keeps `node-scrapy` basic behavior: treating strings as CSS selectors and defaulting the content getter to `textContent`. As seen in tests 01, 03, and 04:


```json
"title"
---
"Basic String Model"
```

```json
{
  "pageTitle": "title",
  "pageHeading": "h1",
  "mainParagraph": ".main-p",
  "secondParagraph": ".second-p"
}
---
{
  "pageTitle": "Single Level Objects",
  "pageHeading": "Main Page Heading",
  "mainParagraph": "Main Paragraph",
  "secondParagraph": "Second Paragraph"
}
```

```json
{
  "pageDetails": {
    "pageTitle": "title",
    "pageHeading": "h1"
  },
  "mainContent": {
    "mainParagraph": ".main-p",
    "secondParagraph": ".second-p"
  }
}
---
{
  "pageDetails": {
    "pageTitle": "Multi Level Objects",
    "pageHeading": "Main Page Heading"
  },
  "mainContent": {
    "mainParagraph": "Main Paragraph",
    "secondParagraph": "Second Paragraph"
  }
}
```

But makes use of the array in the model to distinct between expected single matches or collections, killing the need for the current [unique](https://github.com/eeshi/node-scrapy#unique) option. See test 02 and 05:

```json
["p"]
---
[
  "First Paragraph",
  "Second Paragraph",
  "Third Paragraph"
]
```

```json
{
  "pageDetails": {
    "pageTitle": "title",
    "pageHeading": "h1"
  },
  "mainContent": {
    "mainParagraph": ".main-p",
    "secondParagraph": ".second-p",
    "links": ["a[href]"]
  }
}
---
{
  "pageDetails": {
    "pageTitle": "Multi Level Objects with Array",
    "pageHeading": "Main Page Heading"
  },
  "mainContent": {
    "mainParagraph": "Main Paragraph",
    "secondParagraph": "Second Paragraph",
    "links": ["Paragraph", "lots", "and scrapy should catch them all"]
  }
}
```

The critical part of  this is the fact that since the array on the model only indicates quantity and only the first value of the array counts as the selector, we can use the second index to pass a model object. In this case, the model will match the result and the selector will be the context. See test 08:

```json
{
  "list-title": "title",
  "people": [".person",
    {
      "name": ".name",
      "birthday": ".birthday",
      "languages": [":parent ul > li"]
    }
  ]
}
---
{
  "list-title": "Array of Objects",
  "people": [
    {
      "name": "Stefan",
      "birthday": "1694-03-29",
      "languages": ["shell", "javascript", "german"]
    },
    {
      "name": "Adrian",
      "birthday": "1718-12-03",
      "languages": ["rust", "javascript", "italian"]
    }
  ]
}
```

Also notice that with this approach, the model/result object depth is truly preserved.

**Comment by stefanmaric** [comment]
Referencing #6 and #7 since those are being addressed here.

**Comment by stefanmaric** [comment]
I've published this WIP to npm if anyone wants to test it. You can install it using the `next` tag:

```shell
 npm install node-scrapy@next
```

**Comment by stefanmaric** [comment]
For long time, I was thinking about extending the selector string to reflect both, what piece of the element to take (text nodes, text content, html, attribute, etc) and the transformations to apply (trim, cast, etc), getting rid of nested objects to declare those properties. Then I googled a bit to get inspiration and found [x-ray](https://github.com/lapwinglabs/x-ray), which is pretty popular but I never heard about it before.

`x-ray`'s query language looks something like:

```
'.main-body a @ href | trim:both'
```

where:

```
 '<css selector> @ <getter function or attribute name> | <filter>'
```
Pretty much what I initially thought to implement.

`x-rays`'s query parser ([`x-ray-parse`](https://www.npmjs.com/package/x-ray-parse)) is kind of wonky. Simple queries like this one will break `x-ray`:

```
'p [href*="@google.com"]'
```

I added initial [spec](https://github.com/eeshi/node-scrapy/blob/rework/test/query-parser.test.js) and [implementation](https://github.com/eeshi/node-scrapy/blob/rework/lib/query-parser.js) for `node-scrapy`'s query parser. Spec looks like:

```
'.main-article a => href | trim:both`
```

Implementation is pretty lame so far (still more robust than `x-ray`'s), based on regex splitting and matching. We probably need to base the implementation on something like [peg.js](https://github.com/pegjs/pegjs), [lexer](https://github.com/aaditmshah/lexer), [ohm](https://github.com/harc/ohm), [earley-parser](https://github.com/lagodiuk/earley-parser-js), etc. I've never used any of these (actually, I'm very illiterate on the matter) so I'm open to suggestions/contributions.

**Comment by stefanmaric** [comment]
I've added getters and filters that bring this rework branch to a decent feature parity with master.

I've released version `0.4.0-alpha.1` under the `next` tag. You can install using:

```shell
npm install node-scrapy@next
```

Still to do:

- [ ] throw error on missing filter, or not (it currently does nothing)
- [ ] decide what to do when a selector gets no match: throw error or null fill? (it's currently unhandled and breaking)
- [ ] think about a "strict" mode, related to the points above. For a given instance? Or per-item basis?
- [ ] use something better than regex matching for query-parser implementation
- [ ] isomorphic support when `css-select`'s adapter option gets stable. See: https://github.com/fb55/css-select/pull/66 and https://github.com/nrkn/css-select-browser-adapter and https://github.com/fb55/css-select/commit/e3aac04569197a9ee770a8aeadc3563f1eb85132
- [ ] better tests implementation; too many files with repeated code on `test/` folder right now
- [ ] update README with more substantial information
- [ ] consider doc generation using `jsdoc`/`documentation`, useful to better document getters and filters

**Comment by rybnik** [comment]
@stefanmaric outstanding work, I really like the model syntax! Thank you for your awesome contribution. 

I've been testing the rework branch and I've encountered some problems when no matches are found, particularly on `resolveGetter (getters, query)` from `extract.js` on line [89](https://github.com/eeshi/node-scrapy/blob/rework/lib/extract.js#L89) the `el` element might be null generating and unhandled exception `TypeError: Cannot read property 'attribs' of null`

**Comment by stefanmaric** [comment]
I've made this the default branch and published v0.4.0

**Pull request closed without merging**
